/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/Index'
import { Route as ContactRouteImport } from './routes/Contact'
import { Route as AboutRouteImport } from './routes/About'

const IndexRoute = IndexRouteImport.update({
  id: '/Index',
  path: '/Index',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/Contact',
  path: '/Contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/About',
  path: '/About',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/About': typeof AboutRoute
  '/Contact': typeof ContactRoute
  '/Index': typeof IndexRoute
}
export interface FileRoutesByTo {
  '/About': typeof AboutRoute
  '/Contact': typeof ContactRoute
  '/Index': typeof IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/About': typeof AboutRoute
  '/Contact': typeof ContactRoute
  '/Index': typeof IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/About' | '/Contact' | '/Index'
  fileRoutesByTo: FileRoutesByTo
  to: '/About' | '/Contact' | '/Index'
  id: '__root__' | '/About' | '/Contact' | '/Index'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  IndexRoute: typeof IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/Index': {
      id: '/Index'
      path: '/Index'
      fullPath: '/Index'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Contact': {
      id: '/Contact'
      path: '/Contact'
      fullPath: '/Contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/About': {
      id: '/About'
      path: '/About'
      fullPath: '/About'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  IndexRoute: IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
